name: Manual dispatch test workflow
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      message:
        description: 'Log Message'
        required: true
        default: 'No message given'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Message: ${{ github.event.inputs.tags }}"
        echo "Ref: ${GITHUB_REF}"

 
